### PR TITLE
Allow visitors to work on views

### PR DESCRIPTION
**Pull request by bplaa-yai**
This PR makes possible to use visitors on views.
Most of the changes consist in using generic templates instead of assuming a vector datatype. Many single action visitor are affected by this change.
Review and comments are welcome.

### CODE REVIEW

**Comment by hosseinmoein** [comment]
These changes were really needed. Now all single action visitors are applicable to views as well.
I only see issues with changes to “DataFrame_get.tcc”.

First, you have removed the optional protective locks for multithreading. They are needed and they are nops by default anyway.

Second, “get_vector<T>()” includes a hash table loop-up on an static hash table. All other access methods such as “at<T>()”, “size<T>()”, … call “get_vector<T>()”. That means all those functions also include a static hash table look-up. That is why I do a ”get_vector<T>()” only once on the top and then operate on the underlying vectors. So, this way I am doing only one static hash table look-up which is also optionally protected by a lock. You are potentially doing 10000’s of hash look ups each time you call “at<T>()” inside a visitor loop.
This is also spilling into the single action visitors where you are passing a HeteroVector to the visitor which forces the visitor to use “at<T>()” which again includes static table look ups. You should pass the underlying vector or view to the visitor.


Regards,
HM

**Comment by bplaa-yai** [comment]
@hosseinmoein thank you for your comments. I get your point regarding get_vector calls, and will try the approach you suggest.
About the lock guarding, while I understand your comment, I was wondering why the locking/release was done outside get_vector rather than inside ?

**Comment by hosseinmoein** [comment]
> About the lock guarding, while I understand your comment, I was wondering why the locking/release was done outside get_vector rather than inside ?

So, consider Hetero<..> things as a general container similar to a std::vector. They are not, by default, thread-safe. Making them thread-safe in general, creates performance issues. But you can protect them when you use them, if necessary. Not all "get_vector<T>()" calls need a lock even in a multithreaded program.

**Comment by bplaa-yai** [comment]
> Not all "get_vector()" calls need a lock even in a multithreaded program.

That's what I was missing. Thanks.

**Comment by bplaa-yai** [comment]
I've reverted the commits e5db08d and 4232552, and pushed a saner changeset 98ebe7e, mostly consisting of templating single action visitors arguments and using autos instead of vectors in visit methods).

**Pull request merged**
