### PR TITLE
These last few commits should correct the issues with the previous situation.

### PR DESCRIPTION
**Pull request by kotoroshinoto**

### CODE REVIEW

**Comment by kotoroshinoto** [comment]
in case you're curious why I was using -Wa,-mbig-obj; MinGW64's g++ 8.10 was complaining that the output objects were too big, or something like that.

**Comment by hosseinmoein** [comment]
> in case you're curious why I was using -Wa,-mbig-obj; MinGW64's g++ 8.10 was complaining that the output objects were too big, or something like that.

hmm, are using the 64bit compiler?

**Comment by kotoroshinoto** [comment]
it ought to be, though perhaps it wasn't doing that by default.

**Comment by hosseinmoein** [comment]
@kotoroshinoto , can you please include your latest changes in the pull request? I think we are missing a few commits.

**Comment by kotoroshinoto** [comment]
Was something broken? I'll check it when i get home. I think my version is just a few commits behind yours, if I pull from upstream the conflicts will probably go away.

**Pull request closed without merging**
