### PR TITLE
Attemp to fix export of symbols in msvc builds & hide all symbols in other compilers

### PR DESCRIPTION
**Pull request by SpaceIm**
While modernizing conan recipe of DataFrame, I've seen the mess of `__declspec(dllexport)` & `__declspec(dllimport)` if MSVC and tried to fix it.

- fix usage of static lib with msvc, it was broken without `LIBRARY_EXPORTS` as an interface definition, which was very weird.
- remove `LIBRARY_API` in front of templates, it doesn't make sense and breaks at consume time with msvc if it sees `__declspec(dllimport)`.
- if shared:
  - at build time : `__declspec(dllexport)` on windows and `__attribute__((visibility("default")))` for other systems
  - at consume time: `__declspec(dllimport)` on windows and `__attribute__((visibility("default")))` for other systems
  - hide all symbols if non-msvc compilers as well
- rename `LIBRARY_API` and `LIBRARY_EXPORTS` to less generic names

Honestly, these macros should live in one header file, included when necessary instead of repeating these macros in each header file.

### CODE REVIEW

**Comment by hosseinmoein** [comment]
Thanks I will take look. 
Unfortunately or fortunately, I don't have access to a Windows development environment. I did all that by assuming or by other people contributing.
Thank you again for fixing it

**Comment by SpaceIm** [comment]
I'll push another commit to rely on https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html, it's neater.

**Comment by SpaceIm** [comment]
Locally on macOS Monterey with AppleClang 13.0, I've built all the targets with `BUILD_SHARED_LIBS` either OFF or ON, and run the tests successfully. So at least it doesn't seem to break GNU like compilers.

**Comment by hosseinmoein** [comment]
> Locally on macOS Monterey with AppleClang 13.0, I've built all the targets with `BUILD_SHARED_LIBS` either OFF or ON, and run the tests successfully. So at least it doesn't seem to break GNU like compilers.

Does it also work on Ubuntu based gcc?

**Comment by SpaceIm** [comment]
I'll try later. Might be worth setting up your CI to run builds & tests on Ubuntu, macOS and Windows.

**Review by hosseinmoein — APPROVED** [review]

**Review by hosseinmoein — COMMENTED** [review]
@SpaceIm , `DataFrame/DataFrameExports.h` file is missing here

**Comment by SpaceIm** [comment]
This file is created by CMake at generation time.

**Pull request merged**
