### PR TITLE
CMakeLists.txt adjusted to add static option, and work with MinGW; bonus header guards (just in case)

### PR DESCRIPTION
**Pull request by kotoroshinoto**
both UNIX and MSVC won't be defined if compiling using MinGW on windows, leaving the project without a named library target

i wasn't sure if -D _CRT_SECURE_NO_WARNINGS had any meaning at all for GCC, so I left it wrapped up in an if(MSVC) as you had it before.

Otherwise if you define STATIC to a value evaluating as true, it'll make a static library, and shared otherwise.

This is irrespective of being on unix or not. This should work fine.

### CODE REVIEW

**Comment by kotoroshinoto** [comment]
Looking at the appveyor result, I decided to test using MSVC, it indeed fails for me building a shared library, but it works fine for the static one. (becomes Dataframe.lib), which it appears you wanted anyway, given you specified STATIC for MSVC.  I'll set it so the default flag value for STATIC is ON for MSVC. I'll let you figure out if/when/how to get the dll build to work, as that wasn't what your CMakeLists.txt was doing.

**Comment by kotoroshinoto** [comment]
this might give some insight into what was failing for the dll:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/e6badd8c-434a-4c5b-b5c2-1d58f4b5dd81/exporting-const-static-data-members-to-dll?forum=vclanguage


This stackoverflow question mentions defining dllexport stuff: https://stackoverflow.com/questions/19418908/creating-a-portable-library-to-run-on-both-linux-and-windows

and one of the answers mentions this module:
https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html

I'm not much of a windows API person myself, so I've got no particular insight on how to address the MSVC dll output issue.

**Comment by kotoroshinoto** [comment]
MSVC shared lib chokes since the CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS flag only works for exports;

according to: https://cmake.org/cmake/help/v3.4/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html#prop_tgt:WINDOWS_EXPORT_ALL_SYMBOLS

it still wants __declspec(dllimport) to be used when compiling code against global data symbols, such as static members of a class or struct.

**Comment by kotoroshinoto** [comment]
There needs to be some kind of way to do the configuration such that it doesn't include symbols that screw up msvc so that it can do both *.lib and *.dll libraries.

Perhaps some kind of documented preprocessor define to signal a static vs shared build to wrap around the code in the export header. so that a build using -DSTATIC=1 or even a library specific flag like -DDATAFRAME_STATIC=1 would be enough

**Comment by hosseinmoein** [comment]
When I run the build_all.sh script, I get this
```
../include/DataFrame/HeteroVector.h:11:10: fatal error: 'DataFrame_lib_exports.h' file not found
```

I think you have to readjust the `CommonMakefile.mk` file to be able to find `DataFrame_lib_exports.h` file

**Comment by kotoroshinoto** [comment]
I just checked, it put the test configs under the test subdirectory. I probably need to put the cmake commands that list the tests in the top level CMakeLists.txt so it'll find them at the top level.

I'll fix that.

**Pull request merged**
